# Homework 3

Mohammad-Moein Arabi

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Groceries.csv')
df

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  str
 2   itemDescription  38765 non-null  str
dtypes: int64(1), str(2)
memory usage: 908.7 KB

In [5]:
basket = df.groupby(['Member_number', 'Date'])['itemDescription'].apply(list).reset_index()
basket['count'] = len(basket['itemDescription'])
basket

,Member_number,Date,itemDescription,count
0,1000,15-03-2015,"[sausage, whole milk, semi-finished bread, yog...",14963
1,1000,24-06-2014,"[whole milk, pastry, salty snack]",14963
2,1000,24-07-2015,"[canned beer, misc. beverages]",14963
3,1000,25-11-2015,"[sausage, hygiene articles]",14963
4,1000,27-05-2015,"[soda, pickled vegetables]",14963
...,...,...,...,...
14958,4999,24-01-2015,"[tropical fruit, berries, other vegetables, yo...",14963
14959,4999,26-12-2015,"[bottled water, herbs]",14963
14960,5000,09-03-2014,"[fruit/vegetable juice, onions]",14963
14961,5000,10-02-2015,"[soda, root vegetables, semi-finished bread]",14963
14962,5000,16-11-2014,"[bottled beer, other vegetables]",14963

In [6]:
dataset = basket['itemDescription'].tolist()
dataset

[['sausage', 'whole milk', 'semi-finished bread', 'yogurt'],
 ['whole milk', 'pastry', 'salty snack'],
 ['canned beer', 'misc. beverages'],
 ['sausage', 'hygiene articles'],
 ['soda', 'pickled vegetables'],
 ['frankfurter', 'curd'],
 ['sausage', 'whole milk', 'rolls/buns'],
 ['whole milk', 'soda'],
 ['beef', 'white bread'],
 ['frankfurter', 'soda', 'whipped/sour cream'],
 ['frozen vegetables', 'other vegetables'],
 ['butter', 'whole milk'],
 ['tropical fruit', 'sugar'],
 ['butter milk', 'specialty chocolate'],
 ['sausage', 'rolls/buns'],
 ['root vegetables', 'detergent'],
 ['frozen meals', 'dental care'],
 ['rolls/buns', 'rolls/buns'],
 ['dish cleaner', 'cling film/bags'],
 ['canned beer', 'frozen fish'],
 ['other vegetables', 'hygiene articles'],
 ['pip fruit', 'whole milk', 'tropical fruit'],
 ['rolls/buns', 'red/blush wine', 'chocolate'],
 ['other vegetables', 'shopping bags'],
 ['whole milk', 'chocolate', 'packaged fruit/vegetables', 'rolls/buns'],
 ['root vegetables', 'whole milk', 'pastry'],
 ['rolls/buns', 'rolls/buns'],
 ['whipped/sour cream', 'margarine'],
 ['bottled water', 'softener', 'rolls/buns'],
 ['whole milk', 'rice'],
 ['shopping bags', 'skin care'],
 ['whole milk',
  'frankfurter',
  'chicken',
  'frankfurter',
  'flour',
  'chocolate',
  'bottled beer',
  'rolls/buns'],
 ['hamburger meat', 'liquor (appetizer)', 'liver loaf', 'dessert'],
 ['tropical fruit',
  'soda',
  'yogurt',
  'root vegetables',
  'yogurt',
  'domestic eggs',
  'white wine',
  'photo/film'],
 ['herbs', 'yogurt', 'newspapers'],
 ['tropical fruit', 'yogurt'],
 ['pastry', 'ketchup'],
 ['canned fish', 'cocoa drinks'],
 ['pip fruit', 'coffee', 'UHT-milk'],
 ['kitchen towels', 'sliced cheese'],
 ['bottled water', 'specialty bar'],
 ['frankfurter', 'bottled water'],
 ['pip fruit', 'candles', 'rolls/buns'],
 ['curd cheese', 'pastry'],
 ['whole milk',
  'frankfurter',
  'candles',
  'grapes',
  'herbs',
  'other vegetables',
  'yogurt'],
 ['citrus fruit', 'candy', 'bottled water', 'rolls/buns'],
 ['frankfurter', 'yogurt'],
 ['tropical fruit',
  'root vegetables',
  'rolls/buns',
  'onions',
  'shopping bags'],
 ['frozen vegetables', 'brown bread'],
 ['processed cheese', 'whole milk'],
 ['frozen meals', 'whole milk'],
 ['white bread', 'meat', 'domestic eggs', 'roll products '],
 ['root vegetables', 'mayonnaise'],
 ['other vegetables', 'mustard'],
 ['hard cheese', 'napkins', 'bottled water'],
 ['whole milk', 'candy'],
 ['tropical fruit', 'frozen vegetables'],
 ['mustard', 'whipped/sour cream'],
 ['whole milk', 'sausage', 'bottled beer', 'yogurt'],
 ['canned beer', 'cookware'],
 ['hamburger meat', 'butter milk'],
 ['whole milk', 'rolls/buns'],
 ['citrus fruit', 'whole milk'],
 ['salty snack', 'beef'],
 ['fruit/vegetable juice', 'rolls/buns', 'chocolate'],
 ['UHT-milk', 'bottled beer'],
 ['chicken', 'red/blush wine'],
 ['soft cheese', 'pip fruit'],
 ['rolls/buns', 'frankfurter', 'oil', 'pip fruit', 'mayonnaise'],
 ['brown bread', 'pet care'],
 ['other vegetables', 'rolls/buns'],
 ['yogurt', 'beef'],
 ['other vegetables', 'root vegetables'],
 ['soda', 'dessert', 'shopping bags'],
 ['curd', 'long life bakery product'],
 ['beverages', 'domestic eggs'],
 ['butter milk', 'root vegetables'],
 ['berries', 'cake bar'],
 ['hamburger meat', 'red/blush wine'],
 ['canned beer', 'shopping bags'],
 ['canned beer', 'spices', 'rolls/buns', 'frozen fish'],
 ['frozen meals', 'butter', 'newspapers', 'yogurt'],
 ['rolls/buns', 'baking powder'],
 ['liquor', 'curd', 'yogurt', 'tropical fruit'],
 ['sliced cheese', 'butter'],
 ['sausage', 'fruit/vegetable juice'],
 ['beef', 'napkins'],
 ['whole milk', 'whipped/sour cream'],
 ['whipped/sour cream',
  'root vegetables',
  'rolls/buns',
  'packaged fruit/vegetables'],
 ['domestic eggs', 'soda'],
 ['chicken', 'frozen meals'],
 ['male cosmetics', 'curd'],
 ['white bread', 'bottled beer', 'yogurt', 'berries'],
 ['sausage', 'whipped/sour cream', 'specialty bar'],
 ['fish', 'root vegetables', 'tropical fruit', 'other vegetables'],
 ['coffee', 'shopping bags'],
 ['ham', 'cream cheese '],
 ['canned beer', 'UHT-milk'],
 ['sausage', 'dessert', 'rolls/buns', 'pickled vegetables'],
 ['fruit/vegetable juice', 'salty snack', 'candy', 'dental care', 'butter'],
 ['root vegetables', 'long life bakery product'],
 ['citrus fruit', 'yogurt'],
 ['root vegetables', 'whipped/sour cream', 'root vegetables', 'canned beer'],
 ['softener', 'salt', 'whole milk'],
 ['pork', 'hamburger meat'],
 ['rolls/buns', 'bottled water'],
 ['rolls/buns', 'red/blush wine'],
 ['onions', 'canned beer', 'flower (seeds)'],
 ['rolls/buns', 'sugar'],
 ['soda', 'butter'],
 ['specialty chocolate', 'root vegetables'],
 ['rolls/buns', 'baking powder', 'onions', 'bottled water'],
 ['dessert', 'ham'],
 ['ice cream', 'pot plants'],
 ['other vegetables', 'other vegetables', 'berries'],
 ['beverages', 'cream cheese '],
 ['ice cream', 'whipped/sour cream'],
 ['berries',
  'soda',
  'butter',
  'other vegetables',
  'white bread',
  'cream cheese '],
 ['yogurt', 'root vegetables'],
 ['white bread', 'whole milk', 'pastry', 'shopping bags'],
 ['whipped/sour cream', 'newspapers'],
 ['frankfurter', 'pastry'],
 ['chicken', 'waffles'],
 ['fruit/vegetable juice', 'dessert'],
 ['sausage', 'snack products', 'rolls/buns'],
 ['tropical fruit', 'soda', 'rolls/buns'],
 ['tropical fruit', 'newspapers'],
 ['pip fruit', 'cling film/bags', 'yogurt', 'cat food'],
 ['bottled water', 'domestic eggs', 'frozen meals'],
 ['whole milk', 'newspapers'],
 ['pip fruit', 'white wine', 'white bread', 'salt'],
 ['sausage', 'frozen vegetables'],
 ['whole milk', 'yogurt', 'yogurt', 'rolls/buns'],
 ['whole milk', 'frozen vegetables'],
 ['fruit/vegetable juice', 'vinegar'],
 ['citrus fruit', 'shopping bags', 'chewing gum', 'cake bar'],
 ['frankfurter', 'yogurt', 'canned beer'],
 ['tropical fruit', 'white bread', 'rolls/buns'],
 ['whole milk', 'pip fruit', 'whipped/sour cream'],
 ['other vegetables', 'specialty chocolate'],
 ['Instant food products', 'whipped/sour cream', 'butter', 'cake bar'],
 ['sausage', 'pork', 'butter', 'whole milk', 'fruit/vegetable juice'],
 ['pip fruit', 'herbs', 'frozen meals'],
 ['margarine', 'napkins'],
 ['salty snack', 'rolls/buns'],
 ['whole milk', 'pasta', 'rolls/buns'],
 ['yogurt', 'rolls/buns'],
 ['root vegetables', 'white bread'],
 ['tropical fruit', 'chicken', 'onions', 'packaged fruit/vegetables'],
 ['hamburger meat', 'yogurt'],
 ['prosecco', 'dessert'],
 ['chicken', 'frozen vegetables', 'candy'],
 ['tropical fruit', 'brown bread', 'whole milk'],
 ['beef', 'dessert'],
 ['whole milk', 'other vegetables'],
 ['citrus fruit', 'bottled water'],
 ['citrus fruit', 'rolls/buns', 'whole milk'],
 ['tropical fruit', 'sliced cheese'],
 ['napkins', 'whole milk', 'chocolate marshmallow'],
 ['tropical fruit', 'other vegetables'],
 ['root vegetables', 'curd'],
 ['fruit/vegetable juice', 'specialty chocolate', 'Instant food products'],
 ['root vegetables', 'yogurt', 'butter', 'yogurt'],
 ['chicken', 'onions'],
 ['whole milk', 'pastry'],
 ['pork', 'bottled water'],
 ['curd', 'soda'],
 ['sweet spreads', 'butter'],
 ['pip fruit', 'soda'],
 ['rolls/buns', 'condensed milk', 'whole milk', 'soda'],
 ['rolls/buns', 'tropical fruit'],
 ['butter', 'whole milk'],
 ['white bread', 'candy'],
 ['frankfurter', 'herbs'],
 ['specialty bar', 'margarine'],
 ['meat', 'whole milk'],
 ['house keeping products', 'yogurt'],
 ['whipped/sour cream', 'hygiene articles'],
 ['UHT-milk', 'other vegetables', 'dishes'],
 ['waffles', 'beverages'],
 ['pasta', 'yogurt', 'cat food'],
 ['fish', 'tropical fruit', 'red/blush wine', 'cream cheese '],
 ['other vegetables', 'soda', 'rolls/buns', 'dishes'],
 ['tropical fruit',
  'other vegetables',
  'hamburger meat',
  'popcorn',
  'female sanitary products'],
 ['hamburger meat', 'bottled beer'],
 ['pork', 'coffee', 'frozen vegetables'],
 ['shopping bags', 'shopping bags'],
 ['beef', 'shopping bags'],
 ['soda', 'hamburger meat'],
 ['butter milk', 'yogurt', 'yogurt', 'margarine'],
 ['soda', 'whole milk'],
 ['root vegetables', 'grapes'],
 ['frankfurter', 'whipped/sour cream'],
 ['bottled water', 'chewing gum'],
 ['chicken', 'beverages', 'coffee'],
 ['pork',
  'other vegetables',
  'yogurt',
  'shopping bags',
  'soft cheese',
  'detergent'],
 ['butter', 'dog food'],
 ['chicken', 'frozen vegetables'],
 ['hamburger meat', 'pastry'],
 ['other vegetables', 'whole milk'],
 ['waffles', 'rolls/buns'],
 ['whole milk', 'sugar'],
 ['soda', 'soda'],
 ['bottled beer', 'oil'],
 ['frankfurter', 'citrus fruit', 'margarine'],
 ['soda', 'fruit/vegetable juice'],
 ['photo/film', 'other vegetables'],
 ['pork', 'white wine'],
 ['bottled water', 'yogurt', 'newspapers', 'soda'],
 ['whipped/sour cream', 'meat spreads'],
 ['pip fruit', 'other vegetables'],
 ['ham', 'whole milk'],
 ['salty snack', 'pickled vegetables'],
 ['soda', 'domestic eggs', 'sliced cheese', 'soda'],
 ['tropical fruit', 'UHT-milk'],
 ['sausage', 'bottled water'],
 ['yogurt', 'root vegetables'],
 ['root vegetables', 'other vegetables'],
 ['chicken', 'other vegetables'],
 ['dessert', 'spread cheese'],
 ['sausage', 'salty snack', 'cling film/bags'],
 ['whole milk',
  'tropical fruit',
  'root vegetables',
  'Instant food products',
  'margarine'],
 ['soda', 'fruit/vegetable juice', 'bottled beer'],
 ['beef', 'chocolate'],
 ['beverages', 'dessert'],
 ['whipped/sour cream', 'hard cheese'],
 ['ham', 'whipped/sour cream', 'ketchup'],
 ['white bread', 'frozen fruits'],
 ['tropical fruit',
  'whole milk',
  'other vegetables',
  'long life bakery product'],
 ['other vegetables', 'yogurt', 'whole milk', 'butter', 'shopping bags'],
 ['whole milk', 'sauces'],
 ['whole milk', 'citrus fruit'],
 ['rolls/buns', 'candy'],
 ['root vegetables', 'whole milk'],
 ['cream cheese ', 'rolls/buns'],
 ['long life bakery product', 'root vegetables', 'other vegetables'],
 ['tropical fruit', 'rolls/buns'],
 ['frankfurter', 'tropical fruit'],
 ['tropical fruit', 'whole milk', 'long life bakery product', 'rum'],
 ['hamburger meat', 'soda'],
 ['red/blush wine', 'frozen fish'],
 ['beef', 'dessert'],
 ['root vegetables', 'bottled beer'],
 ['oil', 'shopping bags'],
 ['whole milk', 'other vegetables'],
 ['whole milk', 'tropical fruit'],
 ['hamburger meat', 'pork'],
 ['rolls/buns', 'tropical fruit', 'coffee', 'chocolate'],
 ['pork', 'spread cheese'],
 ['soda', 'yogurt'],
 ['salt', 'domestic eggs'],
 ['pork', 'rolls/buns'],
 ['brown bread', 'fruit/vegetable juice'],
 ['bottled beer', 'tropical fruit', 'sliced cheese', 'dishes'],
 ['cream cheese ', 'newspapers'],
 ['citrus fruit', 'red/blush wine'],
 ['yogurt', 'roll products ', 'fruit/vegetable juice'],
 ['ham', 'other vegetables'],
 ['frankfurter', 'canned beer'],
 ['finished products', 'brown bread', 'dishes'],
 ['yogurt', 'bottled water', 'domestic eggs'],
 ['pip fruit', 'curd', 'pip fruit', 'prosecco'],
 ['brown bread', 'salt'],
 ['semi-finished bread', 'ketchup'],
 ['oil', 'shopping bags'],
 ['fruit/vegetable juice', 'flower (seeds)'],
 ['misc. beverages', 'instant coffee'],
 ['detergent', 'candy'],
 ['UHT-milk', 'canned fish'],
 ['frankfurter', 'citrus fruit', 'bottled water', 'fruit/vegetable juice'],
 ['frankfurter', 'frozen meals', 'dishes'],
 ['pip fruit', 'rolls/buns'],
 ['sausage', 'butter', 'bottled water'],
 ['frankfurter', 'chicken', 'butter', 'bottled water'],
 ['ham', 'whole milk', 'whole milk', 'coffee'],
 ['sausage', 'brown bread'],
 ['other vegetables', 'butter'],
 ['tropical fruit', 'soda'],
 ['pastry', 'pasta'],
 ['white bread', 'brown bread'],
 ['canned beer', 'rolls/buns', 'artif. sweetener', 'soda'],
 ['rolls/buns', 'root vegetables'],
 ['chicken', 'soda'],
 ['frankfurter', 'curd', 'white bread', 'rolls/buns', 'coffee'],
 ['red/blush wine', 'bottled water', 'sweet spreads'],
 ['rolls/buns', 'onions', 'napkins'],
 ['canned beer', 'soda'],
 ['root vegetables', 'frozen vegetables', 'pet care'],
 ['specialty bar',
  'tropical fruit',
  'yogurt',
  'bottled beer',
  'baking powder'],
 ['other vegetables', 'frankfurter', 'newspapers', 'whole milk', 'pastry'],
 ['beverages', 'yogurt'],
 ['tropical fruit', 'whole milk'],
 ['coffee', 'butter milk'],
 ['beef', 'margarine', 'other vegetables'],
 ['bottled water', 'hygiene articles'],
 ['pork', 'sliced cheese'],
 ['specialty chocolate', 'soda', 'bathroom cleaner'],
 ['hamburger meat', 'whole milk'],
 ['pip fruit', 'other vegetables'],
 ['root vegetables', 'citrus fruit'],
 ['other vegetables', 'shopping bags', 'soda'],
 ['yogurt', 'newspapers'],
 ['ice cream', 'whipped/sour cream'],
 ['other vegetables', 'beef', 'soda', 'curd', 'butter'],
 ['canned beer', 'herbs', 'margarine'],
 ['rolls/buns', 'soda'],
 ['rolls/buns', 'citrus fruit'],
 ['coffee', 'berries'],
 ['ham', 'white bread'],
 ['herbs', 'pot plants', 'cake bar'],
 ['soda', 'flower (seeds)', 'jam'],
 ['sausage', 'pip fruit', 'chocolate'],
 ['specialty chocolate', 'white bread'],
 ['whole milk', 'whole milk'],
 ['other vegetables', 'whole milk'],
 ['sausage', 'beverages'],
 ['whole milk', 'hard cheese'],
 ['yogurt', 'berries'],
 ['tropical fruit',
  'meat',
  'other vegetables',
  'domestic eggs',
  'baking powder'],
 ['yogurt', 'sauces'],
 ['beef', 'yogurt'],
 ['ice cream', 'whole milk'],
 ['sausage',
  'whisky',
  'specialty chocolate',
  'dishes',
  'yogurt',
  'napkins',
  'detergent',
  'pastry'],
 ['photo/film', 'shopping bags'],
 ['frankfurter', 'other vegetables', 'bottled beer'],
 ['yogurt', 'newspapers'],
 ['root vegetables',
  'soda',
  'specialty bar',
  'other vegetables',
  'frozen vegetables'],
 ['rolls/buns',
  'grapes',
  'bottled beer',
  'sausage',
  'salty snack',
  'Instant food products',
  'domestic eggs',
  'bottled water'],
 ['dessert', 'domestic eggs'],
 ['sausage', 'tropical fruit', 'misc. beverages', 'root vegetables'],
 ['sausage', 'whole milk'],
 ['whole milk', 'brown bread'],
 ['hamburger meat', 'detergent', 'flour'],
 ['tropical fruit', 'soda'],
 ['newspapers', 'salty snack'],
 ['pasta', 'whole milk', 'waffles'],
 ['chocolate marshmallow', 'other vegetables'],
 ['pickled vegetables', 'flour'],
 ['yogurt', 'shopping bags'],
 ['packaged fruit/vegetables', 'bottled water', 'pork', 'domestic eggs'],
 ['pip fruit', 'fruit/vegetable juice'],
 ['tropical fruit', 'whole milk', 'soda', 'curd'],
 ['shopping bags', 'root vegetables'],
 ['whipped/sour cream', 'curd', 'shopping bags'],
 ['sausage', 'whole milk', 'cake bar'],
 ['frankfurter', 'whipped/sour cream', 'bottled water'],
 ['hard cheese', 'whole milk'],
 ['tropical fruit',
  'citrus fruit',
  'yogurt',
  'frankfurter',
  'specialty chocolate',
  'hard cheese',
  'whole milk',
  'canned beer'],
 ['canned beer', 'napkins', 'rolls/buns'],
 ['grapes', 'other vegetables'],
 ['rolls/buns', 'shopping bags', 'cat food'],
 ['tropical fruit', 'candy'],
 ['citrus fruit', 'dessert'],
 ['root vegetables', 'frozen vegetables', 'bottled water', 'cat food'],
 ['spread cheese', 'pork'],
 ['pip fruit', 'brown bread'],
 ['root vegetables', 'instant coffee'],
 ['soda',
  'hygiene articles',
  'grapes',
  'pudding powder',
  'butter milk',
  'butter'],
 ['whole milk', 'yogurt'],
 ['hamburger meat', 'pasta'],
 ['whole milk', 'processed cheese'],
 ['brown bread', 'sparkling wine'],
 ['rolls/buns', 'other vegetables', 'whipped/sour cream'],
 ['candy', 'white wine'],
 ['root vegetables', 'frozen vegetables'],
 ['other vegetables', 'white bread', 'detergent'],
 ['yogurt', 'beverages', 'brown bread'],
 ['ice cream', 'herbs'],
 ['cream', 'yogurt'],
 ['chicken', 'pastry', 'candles'],
 ['waffles', 'hygiene articles', 'tea'],
 ['yogurt', 'other vegetables', 'rolls/buns', 'herbs'],
 ['yogurt', 'root vegetables'],
 ['domestic eggs', 'yogurt'],
 ['pork', 'whole milk'],
 ['other vegetables', 'white bread'],
 ['bottled water', 'yogurt', 'tropical fruit', 'whole milk'],
 ['citrus fruit', 'misc. beverages'],
 ['liver loaf', 'chicken', 'rolls/buns', 'spread cheese', 'shopping bags'],
 ['citrus fruit', 'misc. beverages'],
 ['whole milk', 'pastry'],
 ['onions', 'newspapers'],
 ['beef', 'specialty fat', 'newspapers'],
 ['rolls/buns', 'semi-finished bread'],
 ['shopping bags', 'rolls/buns'],
 ['pastry', 'canned beer', 'whipped/sour cream', 'grapes'],
 ['salty snack', 'pastry', 'oil'],
 ['frozen potato products', 'specialty cheese'],
 ['brown bread', 'whole milk', 'shopping bags'],
 ['citrus fruit', 'frozen vegetables', 'margarine'],
 ['curd', 'sugar'],
 ['chocolate', 'whole milk'],
 ['pip fruit', 'salty snack', 'pastry'],
 ['pip fruit', 'margarine'],
 ['ham', 'yogurt'],
 ['soda', 'salty snack'],
 ['bottled water', 'chocolate'],
 ['pastry', 'baking powder', 'butter', 'margarine', 'curd', 'dishes'],
 ['whole milk', 'soda'],
 ['pickled vegetables', 'liquor'],
 ['margarine', 'yogurt'],
 ['whole milk', 'frozen vegetables', 'soda', 'UHT-milk'],
 ['other vegetables', 'whipped/sour cream'],
 ['beef', 'semi-finished bread'],
 ['bottled water', 'flour', 'sugar'],
 ['dish cleaner', 'ice cream', 'jam', 'newspapers'],
 ['curd', 'canned beer'],
 ['bottled beer', 'specialty bar', 'baking powder'],
 ['whole milk', 'yogurt', 'newspapers'],
 ['pork', 'pudding powder', 'domestic eggs'],
 ['root vegetables', 'shopping bags'],
 ['misc. beverages', 'UHT-milk', 'white bread'],
 ['dog food', 'sausage', 'dessert', 'shopping bags'],
 ['root vegetables', 'citrus fruit'],
 ['chocolate', 'brown bread', 'salty snack'],
 ['chicken', 'shopping bags'],
 ['other vegetables', 'butter'],
 ['whipped/sour cream', 'yogurt'],
 ['other vegetables', 'yogurt'],
 ['turkey', 'root vegetables'],
 ['other vegetables', 'napkins'],
 ['newspapers', 'white bread', 'rolls/buns', 'beverages'],
 ['other vegetables', 'zwieback'],
 ['brown bread', 'butter milk', 'canned vegetables', 'soda'],
 ['chicken', 'bottled water'],
 ['brown bread', 'soda'],
 ['other vegetables',
  'cream cheese ',
  'liquor',
  'root vegetables',
  'newspapers',
  'hard cheese'],
 ['frankfurter', 'rolls/buns'],
 ['meat', 'whole milk', 'whipped/sour cream'],
 ['bottled beer', 'frozen vegetables', 'sliced cheese'],
 ['pip fruit', 'processed cheese', 'canned beer'],
 ['berries', 'condensed milk'],
 ['house keeping products', 'rolls/buns', 'pickled vegetables', 'curd'],
 ['whole milk', 'hair spray', 'butter', 'pastry'],
 ['ham', 'yogurt'],
 ['grapes', 'whole milk'],
 ['meat', 'other vegetables'],
 ['other vegetables', 'specialty bar'],
 ['soda', 'UHT-milk', 'newspapers', 'white bread'],
 ['citrus fruit', 'brown bread'],
 ['tropical fruit', 'sugar'],
 ['pastry',
  'condensed milk',
  'rice',
  'tropical fruit',
  'chocolate marshmallow'],
 ['coffee', 'shopping bags'],
 ['bottled water', 'citrus fruit'],
 ['root vegetables', 'frozen vegetables'],
 ['chicken', 'dishes'],
 ['rolls/buns', 'oil', 'yogurt'],
 ['pork', 'soda', 'canned vegetables'],
 ['pip fruit', 'whole milk'],
 ['frozen vegetables', 'rolls/buns', 'cling film/bags'],
 ['bottled beer', 'hygiene articles'],
 ['yogurt', 'soda'],
 ['rolls/buns', 'margarine'],
 ['condensed milk', 'shopping bags'],
 ['popcorn', 'citrus fruit'],
 ['sausage', 'pastry'],
 ['root vegetables', 'margarine', 'rolls/buns'],
 ['rolls/buns', 'whipped/sour cream'],
 ['newspapers', 'pork', 'root vegetables', 'napkins'],
 ['misc. beverages', 'whole milk', 'long life bakery product'],
 ['citrus fruit', 'soda'],
 ['soda', 'roll products '],
 ['frankfurter', 'rolls/buns', 'shopping bags', 'margarine'],
 ['other vegetables', 'butter', 'pastry', 'UHT-milk'],
 ['meat', 'coffee'],
 ['frankfurter', 'white bread'],
 ['liquor', 'domestic eggs'],
 ['specialty bar', 'soda', 'frozen vegetables', 'frozen vegetables'],
 ['grapes', 'frozen meals', 'flower (seeds)'],
 ['tea', 'yogurt', 'shopping bags', 'brown bread'],
 ['flower (seeds)', 'white wine'],
 ['cream cheese ', 'specialty chocolate'],
 ['whole milk', 'baking powder'],
 ['margarine', 'soda'],
 ['tropical fruit', 'cream cheese ', 'cream cheese '],
 ['yogurt', 'softener'],
 ['bottled water', 'frankfurter', 'dessert', 'root vegetables'],
 ['other vegetables',
  'semi-finished bread',
  'other vegetables',
  'rolls/buns',
  'shopping bags',
  'salty snack'],
 ['soda', 'whole milk'],

برای اجرای الگوریتم نیاز داریم تا تبدیل به one hot شود

In [7]:
from mlxtend.preprocessing import TransactionEncoder

encoder = TransactionEncoder()
one_hot = encoder.fit(dataset).transform(dataset)
one_hot

array([[False, False, False, ...,  True,  True, False],
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]],
      shape=(14963, 167))

ستون‌های موجود

In [8]:
encoder.columns_

['Instant food products',
 'UHT-milk',
 'abrasive cleaner',
 'artif. sweetener',
 'baby cosmetics',
 'bags',
 'baking powder',
 'bathroom cleaner',
 'beef',
 'berries',
 'beverages',
 'bottled beer',
 'bottled water',
 'brandy',
 'brown bread',
 'butter',
 'butter milk',
 'cake bar',
 'candles',
 'candy',
 'canned beer',
 'canned fish',
 'canned fruit',
 'canned vegetables',
 'cat food',
 'cereals',
 'chewing gum',
 'chicken',
 'chocolate',
 'chocolate marshmallow',
 'citrus fruit',
 'cleaner',
 'cling film/bags',
 'cocoa drinks',
 'coffee',
 'condensed milk',
 'cooking chocolate',
 'cookware',
 'cream',
 'cream cheese ',
 'curd',
 'curd cheese',
 'decalcifier',
 'dental care',
 'dessert',
 'detergent',
 'dish cleaner',
 'dishes',
 'dog food',
 'domestic eggs',
 'female sanitary products',
 'finished products',
 'fish',
 'flour',
 'flower (seeds)',
 'flower soil/fertilizer',
 'frankfurter',
 'frozen chicken',
 'frozen dessert',
 'frozen fish',
 'frozen fruits',
 'frozen meals',
 'frozen potato products',
 'frozen vegetables',
 'fruit/vegetable juice',
 'grapes',
 'hair spray',
 'ham',
 'hamburger meat',
 'hard cheese',
 'herbs',
 'honey',
 'house keeping products',
 'hygiene articles',
 'ice cream',
 'instant coffee',
 'jam',
 'ketchup',
 'kitchen towels',
 'kitchen utensil',
 'light bulbs',
 'liqueur',
 'liquor',
 'liquor (appetizer)',
 'liver loaf',
 'long life bakery product',
 'make up remover',
 'male cosmetics',
 'margarine',
 'mayonnaise',
 'meat',
 'meat spreads',
 'misc. beverages',
 'mustard',
 'napkins',
 'newspapers',
 'nut snack',
 'nuts/prunes',
 'oil',
 'onions',
 'organic products',
 'organic sausage',
 'other vegetables',
 'packaged fruit/vegetables',
 'pasta',
 'pastry',
 'pet care',
 'photo/film',
 'pickled vegetables',
 'pip fruit',
 'popcorn',
 'pork',
 'pot plants',
 'potato products',
 'preservation products',
 'processed cheese',
 'prosecco',
 'pudding powder',
 'ready soups',
 'red/blush wine',
 'rice',
 'roll products ',
 'rolls/buns',
 'root vegetables',
 'rubbing alcohol',
 'rum',
 'salad dressing',
 'salt',
 'salty snack',
 'sauces',
 'sausage',
 'seasonal products',
 'semi-finished bread',
 'shopping bags',
 'skin care',
 'sliced cheese',
 'snack products',
 'soap',
 'soda',
 'soft cheese',
 'softener',
 'soups',
 'sparkling wine',
 'specialty bar',
 'specialty cheese',
 'specialty chocolate',
 'specialty fat',
 'specialty vegetables',
 'spices',
 'spread cheese',
 'sugar',
 'sweet spreads',
 'syrup',
 'tea',
 'tidbits',
 'toilet cleaner',
 'tropical fruit',
 'turkey',
 'vinegar',
 'waffles',
 'whipped/sour cream',
 'whisky',
 'white bread',
 'white wine',
 'whole milk',
 'yogurt',
 'zwieback']

In [9]:
df_one_hot = pd.DataFrame(one_hot, columns=encoder.columns_)
df_one_hot

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14958,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
14959,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14960,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14961,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14962,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
unique_items = len(df['itemDescription'].unique())
frequent = df.groupby('itemDescription').size().sort_values(ascending=False).to_frame('support').reset_index().head(10)
frequent["support_percent"] = frequent["support"] / len(basket) * 100
mean_item_in_basket = df.groupby(['Member_number', 'Date']).size().to_frame('size').reset_index()['size'].mean()


print(f'Count of customers = {len(basket['Member_number'].unique())}')
print(f'Unique items = {unique_items}')
print(f'Mean items in basket = {mean_item_in_basket}')
print('Top-10 most frequent items:')
print(frequent)

Count of customers = 3898
Unique items = 167
Mean items in basket = 2.590723785337165
Top-10 most frequent items:
    itemDescription  support  support_percent
0        whole milk     2502        16.721246
1  other vegetables     1898        12.684622
2        rolls/buns     1716        11.468288
3              soda     1514        10.118292
4            yogurt     1334         8.915324
5   root vegetables     1071         7.157656
6    tropical fruit     1032         6.897013
7     bottled water      933         6.235381
8           sausage      924         6.175232
9      citrus fruit      812         5.426719

min_support = 0.06

In [64]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets_06 = apriori(df_one_hot, min_support=0.06, use_colnames=True)
frequent_itemsets_06['support_count'] = frequent_itemsets_06['support'] * len(basket)
frequent_itemsets_06.sort_values('support', ascending=False)

    support                       itemsets  support_count
7  0.157923        frozenset({whole milk})         2363.0
1  0.122101  frozenset({other vegetables})         1827.0
2  0.110005        frozenset({rolls/buns})         1646.0
5  0.097106              frozenset({soda})         1453.0
8  0.085879            frozenset({yogurt})         1285.0
3  0.069572   frozenset({root vegetables})         1041.0
6  0.067767    frozenset({tropical fruit})         1014.0
0  0.060683     frozenset({bottled water})          908.0
4  0.060349           frozenset({sausage})          903.0

min_support = 0.08

In [65]:

frequent_itemsets_08 = apriori(df_one_hot, min_support=0.08, use_colnames=True)
frequent_itemsets_08.sort_values('support', ascending=False)

    support                       itemsets
3  0.157923        frozenset({whole milk})
0  0.122101  frozenset({other vegetables})
1  0.110005        frozenset({rolls/buns})
2  0.097106              frozenset({soda})
4  0.085879            frozenset({yogurt})

min_support = 0.1

In [66]:

frequent_itemsets_1 = apriori(df_one_hot, min_support=0.1, use_colnames=True)
frequent_itemsets_1.sort_values('support', ascending=False)

    support                       itemsets
2  0.157923        frozenset({whole milk})
0  0.122101  frozenset({other vegetables})
1  0.110005        frozenset({rolls/buns})

In [67]:
for i in range(len(frequent_itemsets_06)):
    print(len(frequent_itemsets_06['itemsets'][i]))

1
1
1
1
1
1
1
1
1

In [68]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df_one_hot, min_support=0.01, use_colnames=True)
frequent_itemsets

     support                                   itemsets
0   0.021386                      frozenset({UHT-milk})
1   0.033950                          frozenset({beef})
2   0.021787                       frozenset({berries})
3   0.016574                     frozenset({beverages})
4   0.045312                  frozenset({bottled beer})
..       ...                                        ...
64  0.010559  frozenset({other vegetables, rolls/buns})
65  0.014837  frozenset({other vegetables, whole milk})
66  0.013968        frozenset({whole milk, rolls/buns})
67  0.011629              frozenset({whole milk, soda})
68  0.011161            frozenset({whole milk, yogurt})

[69 rows x 2 columns]

In [69]:
frequent_itemsets[frequent_itemsets['itemsets'].apply(len) == 2]

     support                                   itemsets
64  0.010559  frozenset({other vegetables, rolls/buns})
65  0.014837  frozenset({other vegetables, whole milk})
66  0.013968        frozenset({whole milk, rolls/buns})
67  0.011629              frozenset({whole milk, soda})
68  0.011161            frozenset({whole milk, yogurt})

In [70]:
from mlxtend.frequent_patterns import fpgrowth

In [71]:
frequent_itemsets_06_fp = fpgrowth(df_one_hot, min_support=0.06, use_colnames=True)
frequent_itemsets_06_fp.sort_values('support', ascending=False)

    support                       itemsets
0  0.157923        frozenset({whole milk})
5  0.122101  frozenset({other vegetables})
4  0.110005        frozenset({rolls/buns})
3  0.097106              frozenset({soda})
1  0.085879            frozenset({yogurt})
7  0.069572   frozenset({root vegetables})
6  0.067767    frozenset({tropical fruit})
8  0.060683     frozenset({bottled water})
2  0.060349           frozenset({sausage})

In [72]:
frequent_itemsets_08_fp = fpgrowth(df_one_hot, min_support=0.08, use_colnames=True)
frequent_itemsets_08_fp.sort_values('support', ascending=False)

    support                       itemsets
0  0.157923        frozenset({whole milk})
4  0.122101  frozenset({other vegetables})
3  0.110005        frozenset({rolls/buns})
2  0.097106              frozenset({soda})
1  0.085879            frozenset({yogurt})

In [73]:
frequent_itemsets_1_fp = fpgrowth(df_one_hot, min_support=0.1, use_colnames=True)
frequent_itemsets_1_fp.sort_values('support', ascending=False)

    support                       itemsets
0  0.157923        frozenset({whole milk})
2  0.122101  frozenset({other vegetables})
1  0.110005        frozenset({rolls/buns})

In [75]:
print(f'Count of frequent patters with min_support=0.06: Apriori={len(frequent_itemsets_06)} - FP-Growth={len(frequent_itemsets_06_fp)}')
print(f'Count of frequent patters with min_support=0.08: Apriori={len(frequent_itemsets_08)} - FP-Growth={len(frequent_itemsets_08_fp)}')
print(f'Count of frequent patters with min_support=0.1: Apriori={len(frequent_itemsets_1)} - FP-Growth={len(frequent_itemsets_1_fp)}')

Count of frequent patters with min_support=0.06: Apriori=9 - FP-Growth=9
Count of frequent patters with min_support=0.08: Apriori=5 - FP-Growth=5
Count of frequent patters with min_support=0.1: Apriori=3 - FP-Growth=3

In [87]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.1)
rules = rules[rules['antecedents'].apply(lambda x: len(x) >= 1) & rules['consequents'].apply(lambda x: len(x) >= 1)]
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift', 'kulczynski']]

,antecedents,consequents,support,confidence,lift,kulczynski
0,frozenset({other vegetables}),frozenset({whole milk}),0.014837,0.121511,0.769430,0.107730
1,frozenset({rolls/buns}),frozenset({whole milk}),0.013968,0.126974,0.804028,0.107711
2,frozenset({soda}),frozenset({whole milk}),0.011629,0.119752,0.758296,0.096694
3,frozenset({yogurt}),frozenset({whole milk}),0.011161,0.129961,0.822940,0.100317